### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by iandonovan** [dkniffin/apprenticeship_bookstore_app#1]
Hi Derek!

I'm leaving these notes here so that we can discuss them tomorrow. Please do not at all think I expect you to even look at this until the morning.

Overall, the app is extremely good. I'm impressed. The notes below are minor, but could definitely use a bit of refactoring. They're very common pitfalls, as well, so I wouldn't be too concerned.
1. You've got a use of `!important` in the orders css. Please never, ever use `!important`.
2. Do you need all of those actions in the `books_controller`? Remember, ActiveAdmin is taking care of your creation, updating, and deleting -- unless you want non-admins to be able to create inventory.
3. The `line_items_controller` is excellent.
4. The `orders_controller` can be split up a bit, I think. Whenever I see more than one set of strong parameters in a controller, it tells me the controller is creating more than one kind of object, which is a bit of a smell. Let's see if we can move `line_item_params` and `user_params` into separate controllers. (It might not be possible! But I think it is.)
5. I have not thought through all the possibilities here, but generally speaking, what are your thoughts on using `respond_with` instead of the repeated `respond_to do` blocks? I bring it up for two reasons:
   1. There's a bit of repetition from method to method where the five lines can be condensed into one
   2. There are a few instances of your `format :json` block doing something involving HTML, like rendering a page -- this is a no-no, as the `json` format should only ever render JSON. This might actually be because of `jbuilder`, which I don't think we use too much around here. Rails 5, in rolling up `rails-api` into its innards, will be using `ActiveModelSerializers`.
6. In the order mailer, super-minor point: the `mail to` call doesn't have to have the email address in a string.
7. Your models are, generally, very good. I like how thin they are. I have some minor points about the Order model:
   1. In the `total` method, you've got `line_items.length`. Use `count` here, as it'll be slightly quicker, since it does a COUNT query on the database, rather than loading all the records and doing a `length`.
   2. In `completed?`, instead of checking that the token is not nil, you can use a Ruby idiom -- `!!stripe_token`, or even `stripe_token.present?`. I generally avoid double-negatives.
8. Looking at your views, two thoughts strike me:
   1. These are extremely good
   2. A lot of these can be deleted, as they're templates for actions your routefile doesn't support. This is related to item #2 above: We can clear out a lot of this functionality, since the CRUD actions for books are supported only through the admin panel.
9. Your test suite is expansive and good.

**Comment by dkniffin** [comment]
Finished all of these.
